version: '2'
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo17:
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
      - "${ODOO_CHAT_PORT}:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - ODOO_ADMIN_PASSWORD=${ODOO_ADMIN_PASSWORD}
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh   # replaces the original entrypoint, refer to odoo docker image for updates
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: unless-stopped             # run as a service
    